-- ----------------------------------------------------------
-- MDB Tools - A library for reading MS Access database files
-- Copyright (C) 2000-2011 Brian Bruns and others.
-- Files in libmdb are licensed under LGPL and the utilities under
-- the GPL, see COPYING.LIB and COPYING files respectively.
-- Check out http://mdbtools.sourceforge.net
-- ----------------------------------------------------------

-- Create tables to hold raw unredacted data as supplied by DOJ&CD in schema trcdbr_raw, owned by user trcdbr_raw.
-- Grant read-only usage on all the tables to trcdbr_prod.

-- Run this as 'psql -h [hostname] -U trcdbr_raw -d trcdbr --echo-all --file=create_tables_trcdbr_accdb_schema.sql'

SET client_encoding = 'UTF-8';

CREATE TABLE trcdbr_raw."dbo_ACTION_TYPES" (
	"CODE"			VARCHAR (120), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_ACTIONS" (
	"CODE"			VARCHAR (120), 
	"DESCRIPTION"		VARCHAR (120), 
	"ACTION_TYPE"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_ACTS" (
	"REF_NO"		VARCHAR (30), 
	"ACT_SEQ"		INTEGER, 
	"VICTIM"		INTEGER, 
	"ACTION_DESCRIPTION"	TEXT, 
	"ACTION_TYPE"		VARCHAR (20), 
	"ACTION"		VARCHAR (20), 
	"PLACE"		VARCHAR (20), 
	"SPECIFIC_LOCATION"	TEXT, 
	"ACT_DATE"		VARCHAR (17), 
	"DATE_ACCURATE_TO"	VARCHAR (2), 
	"TIME_ACCURATE_TO"	VARCHAR (2), 
	"CIRCUMSTANCES"	TEXT, 
	"REASON"		TEXT, 
	"OUTCOME"		TEXT, 
	"GENDER_MOTIVE"	VARCHAR (510), 
	"GEN_COMMENT"		TEXT, 
	"EVENT_ID"		INTEGER, 
	"VERACITY"		VARCHAR (2), 
	"DAY"			INTEGER, 
	"MONTH"		INTEGER, 
	"YEAR"			INTEGER, 
	"VICTIM_ORG_ID"	INTEGER, 
	"VICTIM_AGE"		INTEGER, 
	"LOCATION_TYPE"	VARCHAR (20), 
	"VICTIM_TYPE"		VARCHAR (20), 
	"OUTCOME_TYPE"	VARCHAR (20), 
	"AMNESTY_FINDING"	VARCHAR (2)
);

CREATE TABLE trcdbr_raw."dbo_ALIASES" (
	"PERSON_ID"		INTEGER, 
	"NAME"			VARCHAR (80)
);

CREATE TABLE trcdbr_raw."dbo_APPLICATIONS" (
	"VICTIM"		DOUBLE PRECISION, 
	"RECIPIENT"		DOUBLE PRECISION, 
	"LETTER_TYPE"		VARCHAR (2), 
	"R_AND_R_REF_NO"	VARCHAR (30), 
	"DATE_CREATED"	VARCHAR (20), 
	"DATE_SENT"		VARCHAR (20), 
	"DATE_RECEIVED"	VARCHAR (20), 
	"APP_STATUS"		VARCHAR (20), 
	"NOTES"		TEXT, 
	"LANG"			VARCHAR (20), 
	"RR_CLUSTER"		VARCHAR (20), 
	"BATCH_NO"		VARCHAR (14), 
	"CONSEQUENCE"		VARCHAR (24), 
	"CONS_OTHER"		TEXT, 
	"DECLARE_DEAD"	VARCHAR (2), 
	"DECEASED_NAME"	VARCHAR (160), 
	"DECEASE_DETAILS"	TEXT, 
	"CONS_DESCRIPTION"	VARCHAR (510), 
	"COMPENSATION_REC"	VARCHAR (2), 
	"COMP_DETAILS"	VARCHAR (510), 
	"INTERVENTIONS"	VARCHAR (30), 
	"PF_PAYMENT"		VARCHAR (2), 
	"PF_AMOUNT"		INTEGER, 
	"INTERVEN_DETAILS"	TEXT, 
	"HARM"			VARCHAR (50), 
	"HARM_DESC"		VARCHAR (510)
);

CREATE TABLE trcdbr_raw."dbo_ASSESSMENTS" (
	"REF_NO"			VARCHAR (30), 
	"ASSESSOR1_NO"		DOUBLE PRECISION, 
	"ASSESSOR2_NO"		DOUBLE PRECISION, 
	"IS_VICTIM"			VARCHAR (2), 
	"APPLICANT"			DOUBLE PRECISION, 
	"HARM_PHYSICAL"		VARCHAR (2), 
	"HARM_MENTAL"			VARCHAR (2), 
	"HARM_EMOTIONAL"		VARCHAR (2), 
	"HARM_PECUNIARY"		VARCHAR (2), 
	"HARM_HUMAN_RIGHTS"		VARCHAR (2), 
	"HARM_DETAILS"		TEXT, 
	"HARDSHIP_EXPERIENCED"	VARCHAR (2), 
	"HARDSHIP_EMOTIONAL"		VARCHAR (2), 
	"HARDSHIP_MEDICAL"		VARCHAR (2), 
	"HARDSHIP_EDUCATIONAL"	VARCHAR (2), 
	"HARDSHIP_HOUSING"		VARCHAR (2), 
	"HARDSHIP_WELFARE"		VARCHAR (2), 
	"HARDSHIP_DETAILS"		TEXT, 
	"INTERVEN_URGENT"		VARCHAR (2), 
	"PROVINCE_INTERVENTION"	VARCHAR (200), 
	"DEATH_CERTIFICATE"		VARCHAR (2), 
	"WRONGLY_ACCUSED"		VARCHAR (2), 
	"WRONGLY_ACCUSED_CLEARED"	VARCHAR (2), 
	"EXCEPTIONAL_CIRCUMSTANCES"	VARCHAR (2), 
	"PEOPLE_IN_NEED"		DOUBLE PRECISION, 
	"INT_COSTLY"			VARCHAR (2), 
	"INT_REQUIRED"		TEXT, 
	"INT_COST"			DOUBLE PRECISION, 
	"ASSESSMENT_URGENT"		VARCHAR (2), 
	"RECOMMENDED_UIR"		DOUBLE PRECISION, 
	"FINDING_BY"			VARCHAR (60), 
	"FINDING_DATE"		VARCHAR (17), 
	"CAPTURER"			DOUBLE PRECISION, 
	"DATE_CAPTURED"		VARCHAR (17)
);

CREATE TABLE trcdbr_raw."dbo_AUDITS" (
	"TRANS_DATE"			VARCHAR(17), 
	"TABLE_NAME"			VARCHAR (64), 
	"OPERATION"			VARCHAR (2), 
	"USER_ID"			VARCHAR (60), 
	"IDENTIFIER"			VARCHAR (510)
);

CREATE TABLE trcdbr_raw."dbo_BATCHES" (
	"BATCH_NO"			VARCHAR (14), 
	"DATE_SENT"			VARCHAR(17), 
	"NOTES"			TEXT
);

CREATE TABLE trcdbr_raw."dbo_BIOGRAPHIES" (
	"PERSON_ID"			INTEGER, 
	"BIOG_SEQ"			INTEGER, 
	"ORG_ID"			INTEGER, 
	"PLACE"			VARCHAR (20), 
	"POSITION"			VARCHAR (80), 
	"SECTION"			VARCHAR (80), 
	"FROM_DATE"			VARCHAR(17), 
	"TO_DATE"			VARCHAR(17), 
	"GEN_COMMENT"			VARCHAR (510)
);

CREATE TABLE trcdbr_raw."dbo_CONSEQUENCE_TYPES" (
	"CODE"			VARCHAR (30), 
	"DESCRIPTION"		VARCHAR (500)
);

CREATE TABLE trcdbr_raw."dbo_CONSEQUENCES" (
	"VICTIM"			DOUBLE PRECISION, 
	"RECIPIENT"			DOUBLE PRECISION, 
	"LETTER_TYPE"			VARCHAR (2), 
	"CONSEQUENCE_CODE"		VARCHAR (30), 
	"DETAILS"			TEXT, 
	"ATTACHED"			VARCHAR (2)
);

CREATE TABLE trcdbr_raw."dbo_COUNTRIES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_DEF_EVENTS" (
	"EVENT_ID"			INTEGER, 
	"TITLE"			VARCHAR (510), 
	"START_DATE"			VARCHAR (17), 
	"END_DATE"			VARCHAR (17), 
	"NOTE"				TEXT, 
	"OWNER"			INTEGER, 
	"TRC_CATEGORY"		VARCHAR (20), 
	"ELEMENTARY"			VARCHAR (2), 
	"ADDRESS_1"			VARCHAR (510), 
	"ADDRESS_2"			VARCHAR (510), 
	"ADDRESS_3"			VARCHAR (510), 
	"PLACE"			VARCHAR (20), 
	"DECISION"			VARCHAR (30), 
	"DECISION_DATE"		VARCHAR (17), 
	"DECISION_SUMMARY"		TEXT, 
	"MANNER"			VARCHAR (20), 
	"GAZETTE"			VARCHAR (30), 
	"GAZETTE_DATE"		VARCHAR (17)
);

CREATE TABLE trcdbr_raw."dbo_DEPENDANTS" (
	"VICTIM_PERSON_ID"		DOUBLE PRECISION, 
	"RECIPIENT"			DOUBLE PRECISION, 
	"LETTER_TYPE"			VARCHAR (2), 
	"RELATION_NATURE"		VARCHAR (20), 
	"FIRST_NAME"			VARCHAR (200), 
	"LAST_NAME"			VARCHAR (200), 
	"AGE"				DOUBLE PRECISION, 
	"GENDER"			VARCHAR (2)
);

CREATE TABLE trcdbr_raw."dbo_EVENT_TIE_UPS" (
	"EVENT_ID"			INTEGER, 
	"SUB_EVENT_ID"		INTEGER, 
	"GEN_COMMENT"			VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_EVT_PROFILE" (
	"PROFILE_ID"				INTEGER, 
	"PROFILE_NAME"			VARCHAR (64), 
	"PROFILE_DESCRIPTION"			VARCHAR (160), 
	"SERVICE_NAME"			VARCHAR (160)
);

CREATE TABLE trcdbr_raw."dbo_EVT_PROFILE_EVENTS" (
	"PROFILE_ID"			INTEGER, 
	"EVENT_ID"			INTEGER, 
	"EVENT_NAME"			VARCHAR (160), 
	"FREQUENCY"			INTEGER, 
	"FREQUENCY_UNITS"		VARCHAR (24), 
	"NUM_ARGS"			INTEGER, 
	"ARGS"				TEXT, 
	"FIXIT_JOB_ID"			DOUBLE PRECISION
);

CREATE TABLE trcdbr_raw."dbo_GRP_PERSONS" (
	"USER_ID"			VARCHAR (60), 
	"GRP_NAME"			VARCHAR (120), 
	"PERSON_ID"			INTEGER
);

CREATE TABLE trcdbr_raw."dbo_HEARING_MANNER" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_ID_TYPES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_INTERVENT" (
	"CODE"			VARCHAR (50), 
	"DESCRIPTION"		VARCHAR (500)
);

CREATE TABLE trcdbr_raw."dbo_INTERVENTIONS" (
	"EVENT_ID"			INTEGER, 
	"INT_SEQ"			INTEGER, 
	"WHO"				INTEGER, 
	"FOR_WHOM"			INTEGER, 
	"INT_DATE"			VARCHAR (17), 
	"PLACE"			VARCHAR (20), 
	"DESCRIPTION"			VARCHAR (120), 
	"RESULT"			VARCHAR (510)
);

CREATE TABLE trcdbr_raw."dbo_LANGS" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_LOCATION_TYPES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_MATCHED_NAME" (
	"PERSON_ID"		INTEGER, 
	"MATCH_PERSON_ID"	INTEGER
);

CREATE TABLE trcdbr_raw."dbo_NATURES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_NEED" (
	"NUMBER_OF_PEOPLE"	INTEGER,
	"AMOUNT"		INTEGER
);

CREATE TABLE trcdbr_raw."dbo_OLD_PROVINCES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_ORG_TYPES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120), 
	"LEVEL0"		VARCHAR (20), 
	"LEVEL1"		VARCHAR (20), 
	"LEVEL2"		VARCHAR (20), 
	"LEVEL3"		VARCHAR (20), 
	"LEVEL4"		VARCHAR (20), 
	"MODUS_OPERANDI"	VARCHAR (20)
);

CREATE TABLE trcdbr_raw."dbo_ORGANISATIONS" (
	"ORG_ID"			INTEGER, 
	"FULL_NAME"			VARCHAR (160), 
	"ACRONYM"			VARCHAR (30), 
	"GEN_COMMENT"			VARCHAR (510), 
	"PARENT_ORG_ID"		INTEGER, 
	"ORG_TYPE"			VARCHAR (20)
);

CREATE TABLE trcdbr_raw."dbo_OTHER_INFOS" (
	"REF_NO"		VARCHAR (30), 
	"INFO_SEQ"		INTEGER, 
	"ATTACHED"		VARCHAR (2), 
	"TYPE"			VARCHAR (80), 
	"DESCRIPTION"		TEXT, 
	"ASSESS_REF_NO"	VARCHAR (30)
);

CREATE TABLE trcdbr_raw."dbo_PARTICIPANT_ROLES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_PARTICIPANTS"
 (
	"EVENT_ID"		INTEGER, 
	"PERSON_ID"		INTEGER, 
	"ROLE"			VARCHAR (20)
);

CREATE TABLE trcdbr_raw."dbo_PERPETRATORS" (
	"REF_NO"		VARCHAR (30), 
	"ACT_SEQ"		INTEGER, 
	"PERSON_ID"		INTEGER, 
	"LANG"			VARCHAR (20), 
	"WEAPON"		VARCHAR (120), 
	"VEHICLE"		VARCHAR (510), 
	"HOW_IDENTIFIED"	TEXT, 
	"IDENTIFYING_CHARS"	TEXT, 
	"PERP_ORG_ID"		INTEGER,
	"LAST_SEEN"		TEXT, 
	"GEN_COMMENT"		TEXT, 
	"SECTION_30_SENT"	VARCHAR (17), 
	"SECTION_30_RECEIVED"	VARCHAR (17), 
	"PERP_FINDING"	VARCHAR (2)
);

CREATE TABLE trcdbr_raw."dbo_PERSONS" (
	"PERSON_ID"		INTEGER, 
	"TITLE"		VARCHAR (80), 
	"LAST_NAME"		VARCHAR (80), 
	"FIRST_NAMES"		VARCHAR (80), 
	"ID_TYPE"		VARCHAR (20), 
	"RACE"			VARCHAR (20), 
	"SEX"			VARCHAR (2), 
	"NATIONALITY"		VARCHAR (80), 
	"LANG"			VARCHAR (20), 
	"DATE_OF_BIRTH"	VARCHAR (17),
	"PLACE_OF_BIRTH"	VARCHAR (20), 
	"MARITAL_STATUS"	VARCHAR (20), 
	"USER_ID"		VARCHAR (60), 
	"GEN_COMMENT"		TEXT, 
	"PRISON_NO"		VARCHAR (50), 
	"PRISON"		VARCHAR (510), 
	"VICTIM_FINDING"	VARCHAR (2), 
	"DATE_FINDING"	VARCHAR (17),
	"ACTION_TYPE"		VARCHAR (20), 
	"URGENCY"		VARCHAR (20), 
	"HARM"			TEXT, 
	"RR_STATUS"		VARCHAR (20), 
	"DATE_SUMMARY"	VARCHAR (17), 
	"SUMMARY_STATUS"	VARCHAR (20), 
	"WRITER"		DOUBLE PRECISION, 
	"FINDING_REF_NO"	VARCHAR (30), 
	"FINDING_ACT_SEQ"	DOUBLE PRECISION, 
	"FINDING_SUMMARY"	TEXT
);

CREATE TABLE trcdbr_raw."dbo_PLACES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120), 
	"PLACE_NAME"		VARCHAR (120), 
	"TRC_AREA"		VARCHAR (20), 
	"OFFICE"		VARCHAR (20), 
	"NEW_PROVINCE"	VARCHAR (20), 
	"OLD_PROVINCE"	VARCHAR (20), 
	"COUNTRY"		VARCHAR (20), 
	"POST_CODE_STR"	VARCHAR (8), 
	"POST_CODE_BOX"	VARCHAR (8), 
	"RURAL_URBAN"		VARCHAR (2)
);

CREATE TABLE trcdbr_raw."dbo_PROTOCOL_TYPES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_R_AND_R_CODES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_R_AND_RS" (
	"REF_NO"		VARCHAR (30), 
	"R_R_SEQ"		INTEGER,
	"GEN_COMMENT"		TEXT, 
	"R_AND_R_CODE"	VARCHAR (20)
);

CREATE TABLE trcdbr_raw."dbo_RELATIONS" (
	"PERSON_ID"		INTEGER, 
	"NATURE"		VARCHAR (20), 
	"RELATED_PERSON_ID"	INTEGER
);

CREATE TABLE trcdbr_raw."dbo_RR_CLUSTERS" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_RR_INTERVENTIONS" (
	"REF_NO"		VARCHAR (30), 
	"INTERVENTION"	VARCHAR (50), 
	"DETAILS"		TEXT
);

CREATE TABLE trcdbr_raw."dbo_RR_OTHER_INFOS" (
	"ATTACHED"		VARCHAR (2), 
	"DESCRIPTION"		TEXT, 
	"INFO_SEQ"		INTEGER, 
	"TYPE"			VARCHAR (80), 
	"VICTIM_PERSON_ID"	DOUBLE PRECISION, 
	"RECIPIENT"		DOUBLE PRECISION, 
	"LETTER_TYPE"		VARCHAR (2)
);

CREATE TABLE trcdbr_raw."dbo_SMP_BLOB" (
	"OWNER"		VARCHAR (64), 
	"ID"			VARCHAR (250), 
	"SUBID"		VARCHAR (250), 
	"LEN"			DOUBLE PRECISION, 
	"DATA"			TEXT
);

CREATE TABLE trcdbr_raw."dbo_SMP_REP_VERSION" (
	"C_COMPONENT"			VARCHAR (510), 
	"C_CURRENT_VERSION"		VARCHAR (510), 
	"C_UNUSED"			VARCHAR (510)
);

CREATE TABLE trcdbr_raw."dbo_SMP_SERVICES" (
	"TYPE"			DOUBLE PRECISION, 
	"CLSID"		VARCHAR (256), 
	"INTNAME"		VARCHAR (256)
);

CREATE TABLE trcdbr_raw."dbo_SOURCE_STATUSES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_SOURCES" (
	"REF_NO"			VARCHAR (30), 
	"PROTOCOL_TYPE"		VARCHAR (20), 
	"INTERVIEW_START"		VARCHAR(17), 
	"PLACE"			VARCHAR (20), 
	"TRC_OFFICE"			VARCHAR (20), 
	"INTERVIEWER"			INTEGER, 
	"INTERVIEWEE"			INTEGER, 
	"LANG"				VARCHAR (20), 
	"CONSENT"			VARCHAR (2), 
	"ATTEND_HEARING"		VARCHAR (2), 
	"NAME_IN_REP"			VARCHAR (2), 
	"PREVIOUS_CONTACT"		VARCHAR (2), 
	"TOTAL_PAGES"			INTEGER, 
	"INTERVIEW_END"		VARCHAR(17), 
	"SOURCE_STATUS"		VARCHAR (20), 
	"DATE_REGISTERED"		VARCHAR(17), 
	"DATE_CAPTURED"		VARCHAR(17), 
	"GEN_COMMENT"			TEXT, 
	"FOR_HEARING"			VARCHAR (2), 
	"FINDING_STATUS"		VARCHAR (2), 
	"AMNESTY_GRANTED"		VARCHAR (2), 
	"NOTE"				TEXT, 
	"PROCESSOR"			INTEGER, 
	"CORROBORATOR"		INTEGER, 
	"COMMISSIONER"		INTEGER, 
	"DATE_CORROBORATED"		VARCHAR(17), 
	"DATE_FINDING"		VARCHAR(17), 
	"CAPTURER"			INTEGER, 
	"GAZETTE_DATE"		VARCHAR(17), 
	"GAZETTE_NO"			VARCHAR (20), 
	"DECISION_NO"			VARCHAR (20), 
	"LEGAL_REPRESENTATION"	VARCHAR (500), 
	"DECISION_SUMMARY"		TEXT, 
	"COMMITTEE_MEMBER"		INTEGER, 
	"EVIDENCE_LEADER"		INTEGER
);

CREATE TABLE trcdbr_raw."dbo_STD_LETTERS" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120), 
	"LETTER_TEXT"		TEXT
);

CREATE TABLE trcdbr_raw."dbo_SUMMARY_STATUSES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_TRC_CATEGORIES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_TRC_OFFICES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_TRUTH_CODE_CONTROLS" (
	"CC_DOMAIN"			VARCHAR (60), 
	"CC_COMMENT"			VARCHAR (480), 
	"CC_NEXT_VALUE"		INTEGER
);

CREATE TABLE trcdbr_raw."dbo_TRUTH_REF_CODES" (
	"RV_LOW_VALUE"			VARCHAR (480), 
	"RV_HIGH_VALUE"		VARCHAR (480), 
	"RV_ABBREVIATION"		VARCHAR (480), 
	"RV_DOMAIN"			VARCHAR (200), 
	"RV_MEANING"			VARCHAR (480), 
	"RV_TYPE"			VARCHAR (20)
);

CREATE TABLE trcdbr_raw."dbo_USER_GRPS" (
	"USER_ID"		VARCHAR (60), 
	"GRP_NAME"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_USERS" (
	"USER_ID"			VARCHAR (60), 
	"USER_NAME"			VARCHAR (80), 
	"JOB_TITLE"			VARCHAR (40), 
	"TRC_OFFICE"			VARCHAR (20)
);

CREATE TABLE trcdbr_raw."dbo_VICTIM_TYPES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_WITNESSES" (
	"REF_NO"			VARCHAR (30), 
	"ACT_SEQ"			INTEGER, 
	"PERSON_ID"			INTEGER, 
	"EYEWITNESS"			VARCHAR (2), 
	"GEN_COMMENT"			TEXT
);

CREATE TABLE trcdbr_raw."dbo_APPLICATION_STATUSES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_DATES" (
	"MONTH"		INTEGER, 
	"YEAR"			INTEGER, 
	"PERIOD"		VARCHAR (18), 
	"HISTORICAL_EVENT"	TEXT, 
	"QUARTER"		VARCHAR (14), 
	"DAY"			DOUBLE PRECISION
);

CREATE TABLE trcdbr_raw."dbo_GRP_SOURCES" (
	"USER_ID"		VARCHAR (60), 
	"GRP_NAME"		VARCHAR (120), 
	"REF_NO"		VARCHAR (30)
);

CREATE TABLE trcdbr_raw."dbo_MATCH_NAMES" (
	"PERSON_ID"		INTEGER, 
	"LAST_NAME"		VARCHAR (80), 
	"LS"			VARCHAR (8), 
	"FIRST_NAMES"		VARCHAR (80), 
	"FS"			VARCHAR (8), 
	"F1"			VARCHAR (80), 
	"F2"			VARCHAR (80), 
	"F3"			VARCHAR (80), 
	"F4"			VARCHAR (80), 
	"F1S"			VARCHAR (8), 
	"F2S"			VARCHAR (8), 
	"F3S"			VARCHAR (8), 
	"F4S"			VARCHAR (8), 
	"LCH"			VARCHAR (80), 
	"F1CH"			VARCHAR (80), 
	"F2CH"			VARCHAR (80), 
	"F3CH"			VARCHAR (80), 
	"F4CH"			VARCHAR (80), 
	"LAST_FIRST"		VARCHAR (2), 
	"LAST_FIRST_SWAP"	VARCHAR (2), 
	"LAST_FIRST_INIT"	VARCHAR (2), 
	"LAST_FIRST_INIT_SWAP"	VARCHAR (2), 
	"LAST_FIRST_SOUNDEX"		VARCHAR (2), 
	"MATCH_STATUS"		VARCHAR (2), 
	"ID_NUMBER"			VARCHAR (80), 
	"MATCH_PERSON_ID"		DOUBLE PRECISION
);

CREATE TABLE trcdbr_raw."dbo_OUTCOME_TYPES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_PROVINCES" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120)
);

CREATE TABLE trcdbr_raw."dbo_SMCONFIGURATION" (
	"ATTRIBUTE"			VARCHAR (40), 
	"VALUE"			TEXT
);

CREATE TABLE trcdbr_raw."dbo_TRC_AREAS" (
	"CODE"			VARCHAR (20), 
	"DESCRIPTION"		VARCHAR (120), 
	"TRC_OFFICE"		VARCHAR (20)
);

-- Lastly, grant access to trcdbr_prod
GRANT USAGE ON SCHEMA trcdbr_raw TO trcdbr_prod;
GRANT SELECT ON ALL TABLES IN SCHEMA trcdbr_raw TO trcdbr_prod;

