mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_ACTION_TYPES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_ACTIONS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_ACTS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_ALIASES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_APPLICATION_STATUSES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_APPLICATIONS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_ASSESSMENTS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_AUDITS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_BATCHES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_BIOGRAPHIES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_CONSEQUENCE_TYPES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_CONSEQUENCES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_COUNTRIES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_DATES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_DEF_EVENTS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_DEPENDANTS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_EVENT_TIE_UPS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_EVT_PROFILE_EVENTS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_EVT_PROFILE | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_GRP_PERSONS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_GRP_SOURCES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_HEARING_MANNER | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_ID_TYPES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_INTERVENT | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_INTERVENTIONS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_LANGS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_LOCATION_TYPES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_MATCH_NAMES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_MATCHED_NAME | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_NATURES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_NEED | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_OLD_PROVINCES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_ORG_TYPES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_ORGANISATIONS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_OTHER_INFOS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_OUTCOME_TYPES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_PARTICIPANT_ROLES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_PARTICIPANTS  | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_PERPETRATORS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_PERSONS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_PLACES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_PROTOCOL_TYPES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_PROVINCES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_R_AND_R_CODES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_R_AND_RS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_RELATIONS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_RR_CLUSTERS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_RR_INTERVENTIONS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_RR_OTHER_INFOS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_SMCONFIGURATION | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_SMP_BLOB | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_SMP_REP_VERSION | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_SMP_SERVICES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_SOURCE_STATUSES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_SOURCES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_STD_LETTERS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_SUMMARY_STATUSES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_TRC_AREAS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_TRC_CATEGORIES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_TRC_OFFICES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_TRUTH_CODE_CONTROLS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_TRUTH_REF_CODES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_USER_GRPS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_USERS | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_VICTIM_TYPES | psql -h gostorage -d trcdbr -U trcdbr_raw
mdb-export -I postgres -q \' TRC_NoPersonalInfo.accdb dbo_WITNESSES | psql -h gostorage -d trcdbr -U trcdbr_raw

